### ISSUE TITLE
[SUGGESTION] restructure Waystone GUI

### ISSUE THREAD

**Issue by vniehues** [SweetRazory/WaystonesPlus#2]
Finally someone made the Waystones Plugin I've been hoping for! 

I know you're in the middle of adding features and restructuring everything but I thought I'd share a suggestion. 

Make the list of Waystones the default screen (most used after initial config)
Move the visibility toggle to the settings screen (after it's implemented)
Move the settings button to one of the corners of the GUI (where you left empty space / made a vignette)

I think these changes should be in line with how people will be using the Waystones once they're set up and configured. 
Needless to say that the rename GUI etc should also be buttons inside the settings screen.

I'm really excited to see where this plugin is headed. Thank you for your work!

**Comment by SweetRazory** [comment]
Hi! Thanks for the suggestion, currently the plugin is in baby shoes, and many many planning goes into how the plugin should go on. I agree that the GUI needs a better "system" and a better feel to it. I'd suggest you join to our discord, then we can actively discuss these updates, and opinions. Thanks for the feedback again! :) https://discord.gg/vHRvwjnt6H

**Comment by vniehues** [comment]
Sound good! :)
